/******************************
脚本名称：布丁锁屏解锁
Version  : v1.0.0
更新时间：2026-05-31
作者：Curtinp118
Platform : Quantumult X
脚本功能：解锁布丁锁屏会员功能
使用说明：添加到重写，打开布丁锁屏App即可生效
*******************************/

[rewrite_local]
^https://screen-lock\.sm-check\.com/ url script-response-body https://raw.githubusercontent.com/curtinp118/Scripthub/main/scripts/buding/buding.js

[MITM]
hostname = screen-lock.sm-check.com
