/******************************
脚本名称：彩云天气解锁
Version  : v1.0.0
更新时间：2026-05-31
作者：Curtinp118
Platform : Quantumult X
脚本功能：解锁彩云天气会员功能
使用说明：添加到重写，打开彩云天气App即可生效
*******************************/

[rewrite_local]
^https://biz\.cyapi\.cn/ url script-response-body https://raw.githubusercontent.com/curtinp118/Scripthub/main/scripts/caiyun/caiyun.js

[MITM]
hostname = biz.cyapi.cn
