/******************************
脚本名称：中国移动签到
Version  : v1.0.0
更新时间：2026-05-31
作者：Curtinp118
Platform : Quantumult X
脚本功能：中国移动App每日签到
使用说明：添加到重写和定时任务，每天8:35自动签到
*******************************/

[rewrite_local]
^https?:\/\/wx\.10086\.cn\/qwhdhub\/ url script-request-header https://raw.githubusercontent.com/curtinp118/Scripthub/main/scripts/cmcc/cmcc.js

[task_local]
35 8 * * * https://raw.githubusercontent.com/curtinp118/Scripthub/main/scripts/cmcc/cmcc.js, tag=中国移动签到, enabled=true

[MITM]
hostname = %APPEND% wx.10086.cn
