/******************************
脚本名称：Nicegram解锁
Version  : v1.0.0
更新时间：2026-05-31
作者：Curtinp118
Platform : Quantumult X
脚本功能：解锁Nicegram会员功能
使用说明：添加到重写，打开Nicegram App即可生效
*******************************/

[rewrite_local]
https://nicegram.cloud/api/v6/user/info url script-response-body https://raw.githubusercontent.com/curtinp118/Scripthub/main/scripts/nicegram/nicegram.js

[MITM]
hostname = nicegram.cloud
